development:
  adapter: postgresql
  encoding: unicode
  database: bootstrap
  pool: 5
  host: localhost
  username: radu
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: bootstrap_production
  pool: 5
  host: localhost
  user: bootstrap
  password: secret
