development:
  adapter: postgresql
  encoding: unicode
  database: raduvlad_development
  pool: 5
  host: localhost
  username: radu
  password: secret

production:
  adapter: postgresql
  encoding: unicode
  database: raduvlad_production
  pool: 5
  host: localhost
  username: bootstrap
  password: secret
